[package]
name = "aklete"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10"
thiserror = "1.0"

[dev-dependencies]
async-std = "1.10"
